# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16aVUj5PvXcbOA3wAe7N35XDJodHTL-ar
"""

pip install streamlit

import io
import zipfile
import numpy as np
import pandas as pd
import streamlit as st
import matplotlib.pyplot as plt

from sklearn.metrics import mean_squared_error
from sklearn.model_selection import StratifiedKFold
from sklearn.inspection import permutation_importance

# LightGBM
import lightgbm as lgb

st.set_page_config(page_title="AirQo Dashboard (OOF/Test + LightGBM Explain)", layout="wide")

ID_COL = "ID"
LOC_COL = "location"
TARGET_COL = "target"


# -------------------------
# Utils
# -------------------------
def rmse(y_true, y_pred):
    y_true = np.asarray(y_true).reshape(-1)
    y_pred = np.asarray(y_pred).reshape(-1)
    return float(np.sqrt(mean_squared_error(y_true, y_pred)))


def to_float32(x):
    return np.asarray(x, dtype=np.float32)


def nan_clean(a):
    return np.nan_to_num(np.asarray(a), nan=0.0, posinf=0.0, neginf=0.0)


def fig_hist(series_list, labels, title, bins=60):
    fig = plt.figure(figsize=(10, 4))
    for s, lab in zip(series_list, labels):
        plt.hist(s, bins=bins, alpha=0.6, label=lab)
    plt.title(title)
    plt.legend()
    return fig


def fig_scatter(x, y, title, xlabel, ylabel):
    fig = plt.figure(figsize=(6, 6))
    plt.scatter(x, y, s=6, alpha=0.4)
    mn = float(min(np.min(x), np.min(y)))
    mx = float(max(np.max(x), np.max(y)))
    plt.plot([mn, mx], [mn, mx])
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    return fig


def fig_residuals(pred, resid, title):
    fig = plt.figure(figsize=(10, 4))
    plt.scatter(pred, resid, s=6, alpha=0.4)
    plt.axhline(0.0)
    plt.title(title)
    plt.xlabel("prediction")
    plt.ylabel("residual (y - pred)")
    return fig


def make_zip(files_dict):
    """
    files_dict: {filename: bytes}
    """
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        for fname, content in files_dict.items():
            zf.writestr(fname, content)
    buf.seek(0)
    return buf.getvalue()


# -------------------------
# Loaders
# -------------------------
def load_from_bundle_csv(bundle_df):
    """
    bundle_df must contain a 'section' column with:
      - train_rows
      - test_rows
      - importance_gain (optional)
      - importance_permutation (optional)
    """
    if "section" not in bundle_df.columns:
        raise ValueError("Le CSV bundle doit contenir une colonne 'section'.")

    train_rows = bundle_df[bundle_df["section"] == "train_rows"].copy()
    test_rows = bundle_df[bundle_df["section"] == "test_rows"].copy()

    # Required cols
    for c in [ID_COL, LOC_COL, "y", "oof"]:
        if c not in train_rows.columns:
            raise ValueError(f"train_rows doit contenir la colonne '{c}'.")

    if "test_pred" not in test_rows.columns:
        raise ValueError("test_rows doit contenir la colonne 'test_pred'.")

    # Cast
    y = train_rows["y"].astype(np.float32).values
    oof = train_rows["oof"].astype(np.float32).values
    test_pred = test_rows["test_pred"].astype(np.float32).values

    train_keys = train_rows[[ID_COL, LOC_COL]].copy()
    test_keys = test_rows[[ID_COL, LOC_COL]].copy()

    # Tab columns = everything except known non-feature columns
    non_feature = set(["section", ID_COL, LOC_COL, "y", "oof", "test_pred",
                       "feature", "importance_gain", "perm_mean", "perm_std"])
    tab_cols = [c for c in train_rows.columns if c not in non_feature]

    X_tab_train = train_rows[tab_cols].astype(np.float32).values if len(tab_cols) > 0 else None
    X_tab_test = test_rows[tab_cols].astype(np.float32).values if len(tab_cols) > 0 else None

    tab_feature_names = tab_cols

    # Optional importances
    imp_gain = bundle_df[bundle_df["section"] == "importance_gain"].copy()
    imp_perm = bundle_df[bundle_df["section"] == "importance_permutation"].copy()

    imp_gain_df = None
    imp_perm_df = None
    if "feature" in imp_gain.columns and "importance_gain" in imp_gain.columns and len(imp_gain) > 0:
        imp_gain_df = imp_gain[["feature", "importance_gain"]].dropna()

    if "feature" in imp_perm.columns and "perm_mean" in imp_perm.columns and len(imp_perm) > 0:
        cols = ["feature", "perm_mean"] + (["perm_std"] if "perm_std" in imp_perm.columns else [])
        imp_perm_df = imp_perm[cols].dropna()

    return {
        "y": y,
        "oof": oof,
        "test_pred": test_pred,
        "train_keys": train_keys,
        "test_keys": test_keys,
        "X_tab_train": X_tab_train,
        "X_tab_test": X_tab_test,
        "tab_feature_names": tab_feature_names,
        "imp_gain_df": imp_gain_df,
        "imp_perm_df": imp_perm_df,
    }


def load_from_separate_files(files):
    """
    files: dict of uploaded file objects.
    Expected:
      - oof.npy, y.npy, test_pred.npy
      - train_keys.csv, test_keys.csv
      - X_tab_train.npy, X_tab_test.npy (optional but needed for LightGBM)
      - tab_feature_names.csv (optional but recommended)
      - lgb_importance_gain.csv / permutation csv (optional)
    """
    def read_npy(uploaded):
        return np.load(uploaded)

    def read_csv(uploaded):
        return pd.read_csv(uploaded)

    y = read_npy(files["y.npy"]).astype(np.float32).reshape(-1)
    oof = read_npy(files["oof.npy"]).astype(np.float32).reshape(-1)
    test_pred = read_npy(files["test_pred.npy"]).astype(np.float32).reshape(-1)

    train_keys = read_csv(files["train_keys.csv"])
    test_keys = read_csv(files["test_keys.csv"])

    X_tab_train = None
    X_tab_test = None
    if "X_tab_train.npy" in files and "X_tab_test.npy" in files:
        X_tab_train = nan_clean(read_npy(files["X_tab_train.npy"]).astype(np.float32))
        X_tab_test = nan_clean(read_npy(files["X_tab_test.npy"]).astype(np.float32))

    tab_feature_names = None
    if "tab_feature_names.csv" in files:
        tab_feature_names = pd.read_csv(files["tab_feature_names.csv"], header=None)[0].tolist()

    imp_gain_df = None
    imp_perm_df = None
    if "lgb_importance_gain.csv" in files:
        imp_gain_df = read_csv(files["lgb_importance_gain.csv"])
    if "lgb_importance_permutation.csv" in files:
        imp_perm_df = read_csv(files["lgb_importance_permutation.csv"])

    return {
        "y": y,
        "oof": oof,
        "test_pred": test_pred,
        "train_keys": train_keys,
        "test_keys": test_keys,
        "X_tab_train": X_tab_train,
        "X_tab_test": X_tab_test,
        "tab_feature_names": tab_feature_names,
        "imp_gain_df": imp_gain_df,
        "imp_perm_df": imp_perm_df,
    }


# -------------------------
# Sidebar: Data input
# -------------------------
st.title("AirQo — Dashboard (OOF/Test + Résidus + LightGBM Explainability)")

st.sidebar.header("1) Données / Artefacts")
mode = st.sidebar.radio(
    "Mode de chargement",
    ["Bundle CSV unique (recommandé)", "Fichiers séparés (NPY/CSV)"]
)

data = None

if mode == "Bundle CSV unique (recommandé)":
    up = st.sidebar.file_uploader("Uploader airqo_streamlit_bundle.csv", type=["csv"])
    if up is not None:
        bundle_df = pd.read_csv(up)
        try:
            data = load_from_bundle_csv(bundle_df)
            st.sidebar.success("Bundle chargé ✅")
        except Exception as e:
            st.sidebar.error(f"Erreur bundle: {e}")

else:
    st.sidebar.caption("Uploader au minimum: y.npy, oof.npy, test_pred.npy, train_keys.csv, test_keys.csv")
    up_y = st.sidebar.file_uploader("y.npy", type=["npy"])
    up_oof = st.sidebar.file_uploader("oof.npy", type=["npy"])
    up_testpred = st.sidebar.file_uploader("test_pred.npy", type=["npy"])
    up_trainkeys = st.sidebar.file_uploader("train_keys.csv", type=["csv"])
    up_testkeys = st.sidebar.file_uploader("test_keys.csv", type=["csv"])

    st.sidebar.caption("Optionnel (pour LightGBM): X_tab_train.npy + X_tab_test.npy + tab_feature_names.csv")
    up_xtab_tr = st.sidebar.file_uploader("X_tab_train.npy", type=["npy"])
    up_xtab_te = st.sidebar.file_uploader("X_tab_test.npy", type=["npy"])
    up_names = st.sidebar.file_uploader("tab_feature_names.csv", type=["csv"])

    st.sidebar.caption("Optionnel: importances pré-calculées")
    up_gain = st.sidebar.file_uploader("lgb_importance_gain.csv", type=["csv"])
    up_perm = st.sidebar.file_uploader("lgb_importance_permutation.csv", type=["csv"])

    if all([up_y, up_oof, up_testpred, up_trainkeys, up_testkeys]):
        files = {
            "y.npy": up_y,
            "oof.npy": up_oof,
            "test_pred.npy": up_testpred,
            "train_keys.csv": up_trainkeys,
            "test_keys.csv": up_testkeys,
        }
        if up_xtab_tr and up_xtab_te:
            files["X_tab_train.npy"] = up_xtab_tr
            files["X_tab_test.npy"] = up_xtab_te
        if up_names:
            files["tab_feature_names.csv"] = up_names
        if up_gain:
            files["lgb_importance_gain.csv"] = up_gain
        if up_perm:
            files["lgb_importance_permutation.csv"] = up_perm

        try:
            data = load_from_separate_files(files)
            st.sidebar.success("Fichiers chargés ✅")
        except Exception as e:
            st.sidebar.error(f"Erreur chargement: {e}")

if data is None:
    st.info("Charge tes artefacts via la sidebar pour commencer.")
    st.stop()


# -------------------------
# Core derived tables
# -------------------------
y = data["y"]
oof = data["oof"]
test_pred = data["test_pred"]
train_keys = data["train_keys"]
test_keys = data["test_keys"]
X_tab_train = data["X_tab_train"]
X_tab_test = data["X_tab_test"]
tab_feature_names = data["tab_feature_names"] if data["tab_feature_names"] is not None else (
    data["tab_feature_names"] if isinstance(data["tab_feature_names"], list) else None
)

df_diag = train_keys.copy()
df_diag["y"] = y
df_diag["oof"] = oof
df_diag["resid"] = df_diag["y"] - df_diag["oof"]
df_diag["abs_err"] = np.abs(df_diag["resid"])

# -------------------------
# Tabs
# -------------------------
tab1, tab2, tab3, tab4 = st.tabs([
    "A) OOF/Test + Résidus",
    "B) Erreurs par location",
    "C) LightGBM (train + importances)",
    "D) Export artefacts"
])

# ===== Tab A =====
with tab1:
    c1, c2, c3 = st.columns(3)
    c1.metric("Train OOF RMSE", f"{rmse(y, oof):.4f}")
    c2.metric("Train N", f"{len(y)}")
    c3.metric("Test N", f"{len(test_pred)}")

    st.subheader("Distributions")
    colL, colR = st.columns(2)
    with colL:
        st.pyplot(fig_hist([y, oof], ["y", "OOF pred"], "Distribution: y vs OOF pred"))
    with colR:
        st.pyplot(fig_hist([test_pred], ["test_pred"], "Distribution: test predictions"))

    st.subheader("Calibration (y vs OOF)")
    st.pyplot(fig_scatter(y, oof, "Scatter: y vs OOF pred", "y true", "OOF pred"))

    st.subheader("Résidus")
    colL, colR = st.columns(2)
    with colL:
        fig = plt.figure(figsize=(10,4))
        plt.hist(df_diag["resid"].values, bins=80, alpha=0.85)
        plt.title("Histogramme des résidus (y - oof)")
        st.pyplot(fig)
    with colR:
        st.pyplot(fig_residuals(df_diag["oof"].values, df_diag["resid"].values, "Résidus vs prédiction (OOF)"))

    st.subheader("Top erreurs (inspection)")
    st.dataframe(df_diag.sort_values("abs_err", ascending=False).head(30), use_container_width=True)

# ===== Tab B =====
with tab2:
    st.subheader("Erreurs par location")

    rows = []
    for loc in sorted(df_diag[LOC_COL].astype(str).unique()):
        part = df_diag[df_diag[LOC_COL].astype(str) == loc]
        rows.append({
            "location": loc,
            "n": len(part),
            "rmse": rmse(part["y"].values, part["oof"].values),
            "mae": float(np.mean(np.abs(part["resid"].values))),
            "resid_mean": float(part["resid"].mean()),
            "resid_std": float(part["resid"].std()),
        })
    df_loc = pd.DataFrame(rows).sort_values("rmse", ascending=False)

    st.dataframe(df_loc, use_container_width=True)

    fig = plt.figure(figsize=(8,4))
    plt.bar(df_loc["location"].astype(str), df_loc["rmse"])
    plt.title("RMSE par location (OOF)")
    plt.xlabel("location")
    plt.ylabel("RMSE")
    st.pyplot(fig)

# ===== Tab C =====
with tab3:
    st.subheader("LightGBM sur X_tab (interpretable)")
    st.caption(
        "Ce modèle est entraîné sur X_tab (metadata + stats). "
        "Il sert à expliquer les signaux tabulaires dominants (importance)."
    )

    if X_tab_train is None:
        st.warning("X_tab_train / X_tab_test non disponibles. Charge-les (bundle avec features ou fichiers séparés).")
        st.stop()

    # Feature names
    if tab_feature_names is None:
        # If bundle mode, names are columns inferred; otherwise fallback
        tab_feature_names = [f"f_{i}" for i in range(X_tab_train.shape[1])]

    # Params
    st.sidebar.header("2) Paramètres LightGBM")
    cv_folds = st.sidebar.slider("CV folds", min_value=3, max_value=10, value=5)
    lr = st.sidebar.select_slider("learning_rate", options=[0.005, 0.01, 0.02, 0.05], value=0.02)
    num_leaves = st.sidebar.select_slider("num_leaves", options=[31, 63, 127, 255], value=63)
    subsample = st.sidebar.select_slider("subsample", options=[0.6, 0.7, 0.8, 0.9, 1.0], value=0.8)
    colsample = st.sidebar.select_slider("colsample_bytree", options=[0.6, 0.7, 0.8, 0.9, 1.0], value=0.8)
    n_estim = st.sidebar.select_slider("n_estimators (max)", options=[2000, 5000, 8000], value=5000)
    early = st.sidebar.select_slider("early_stopping rounds", options=[100, 200, 400], value=200)

    do_train = st.button("Lancer entraînement LightGBM (CV + importances)")

    # Hold session state
    if "lgb_results" not in st.session_state:
        st.session_state["lgb_results"] = {}

    if do_train:
        X_clean = nan_clean(X_tab_train).astype(np.float32)
        loc = train_keys[LOC_COL].astype(str).values
        skf = StratifiedKFold(n_splits=cv_folds, shuffle=True, random_state=42)

        params = dict(
            n_estimators=n_estim,
            learning_rate=lr,
            num_leaves=num_leaves,
            subsample=subsample,
            colsample_bytree=colsample,
            random_state=42,
            n_jobs=-1
        )

        oof_lgb = np.zeros(len(X_clean), dtype=np.float32)
        imp_accum = np.zeros(X_clean.shape[1], dtype=np.float64)

        fold_scores = []
        for fold, (tr_idx, va_idx) in enumerate(skf.split(X_clean, loc), 1):
            Xtr, Xva = X_clean[tr_idx], X_clean[va_idx]
            ytr, yva = y[tr_idx], y[va_idx]

            model = lgb.LGBMRegressor(**params)
            model.fit(
                Xtr, ytr,
                eval_set=[(Xva, yva)],
                eval_metric="rmse",
                callbacks=[lgb.early_stopping(early, verbose=False)]
            )

            pred = model.predict(Xva).astype(np.float32)
            oof_lgb[va_idx] = pred
            fold_rmse = rmse(yva, pred)
            fold_scores.append(fold_rmse)

            imp_accum += model.feature_importances_.astype(np.float64)
            st.write(f"[fold {fold}] RMSE: {fold_rmse:.4f}")

        lgb_rmse = rmse(y, oof_lgb)
        st.success(f"LightGBM OOF RMSE = {lgb_rmse:.4f}")

        imp_mean = imp_accum / cv_folds
        imp_df = pd.DataFrame({"feature": tab_feature_names, "importance_gain": imp_mean})
        imp_df = imp_df.sort_values("importance_gain", ascending=False)

        # Permutation importance (single fold for speed)
        st.info("Permutation importance: calculée sur 1 fold (rapide).")
        tr_idx, va_idx = next(skf.split(X_clean, loc))
        Xtr, Xva = X_clean[tr_idx], X_clean[va_idx]
        ytr, yva = y[tr_idx], y[va_idx]

        model_pi = lgb.LGBMRegressor(**params)
        model_pi.fit(
            Xtr, ytr,
            eval_set=[(Xva, yva)],
            eval_metric="rmse",
            callbacks=[lgb.early_stopping(early, verbose=False)]
        )

        # optional subsampling for speed
        max_pi = st.sidebar.select_slider("Permutation sample size", options=[1000, 2000, 3000, 5000, 8000], value=3000)
        n_rep = st.sidebar.select_slider("Permutation repeats", options=[3, 5, 8], value=5)

        if len(Xva) > max_pi:
            rng = np.random.RandomState(42)
            idx = rng.choice(len(Xva), size=max_pi, replace=False)
            Xva_pi = Xva[idx]
            yva_pi = yva[idx]
        else:
            Xva_pi = Xva
            yva_pi = yva

        perm = permutation_importance(
            model_pi, Xva_pi, yva_pi,
            n_repeats=n_rep,
            random_state=42,
            n_jobs=-1
        )

        perm_df = pd.DataFrame({
            "feature": tab_feature_names,
            "perm_mean": perm.importances_mean,
            "perm_std": perm.importances_std
        }).sort_values("perm_mean", ascending=False)

        st.session_state["lgb_results"] = {
            "oof_lgb": oof_lgb,
            "lgb_rmse": lgb_rmse,
            "fold_scores": fold_scores,
            "imp_df": imp_df,
            "perm_df": perm_df
        }

    # Display existing results if available
    res = st.session_state.get("lgb_results", {})
    if res:
        st.subheader("Résultats LightGBM")
        st.write("OOF RMSE:", f"{res['lgb_rmse']:.4f}")
        st.write("Fold RMSE:", [float(f"{x:.4f}") for x in res["fold_scores"]])

        imp_df = res["imp_df"]
        perm_df = res["perm_df"]

        c1, c2 = st.columns(2)
        with c1:
            st.write("Top gain importance")
            st.dataframe(imp_df.head(30), use_container_width=True)
        with c2:
            st.write("Top permutation importance")
            st.dataframe(perm_df.head(30), use_container_width=True)

        # Plots
        topk = 30
        top = imp_df.head(topk).iloc[::-1]
        fig = plt.figure(figsize=(10, 7))
        plt.barh(top["feature"], top["importance_gain"])
        plt.title("LightGBM - Top 30 (gain)")
        st.pyplot(fig)

        topk = 20
        top = perm_df.head(topk).iloc[::-1]
        fig = plt.figure(figsize=(10, 6))
        plt.barh(top["feature"], top["perm_mean"])
        plt.title("Permutation importance - Top 20")
        st.pyplot(fig)

# ===== Tab D =====
with tab4:
    st.subheader("Exporter les artefacts (download)")

    st.caption(
        "Streamlit Community Cloud ne garantit pas l'écriture persistante sur disque. "
        "Donc on génère les fichiers en mémoire et on te propose un ZIP à télécharger."
    )

    # Base artifacts always available
    files_out = {}

    # CSV diagnostics
    df_loc_rows = []
    for loc in sorted(df_diag[LOC_COL].astype(str).unique()):
        part = df_diag[df_diag[LOC_COL].astype(str) == loc]
        df_loc_rows.append({
            "location": loc,
            "n": len(part),
            "rmse": rmse(part["y"].values, part["oof"].values),
            "mae": float(np.mean(np.abs(part["resid"].values))),
            "resid_mean": float(part["resid"].mean()),
            "resid_std": float(part["resid"].std()),
        })
    df_loc_export = pd.DataFrame(df_loc_rows).sort_values("rmse", ascending=False)

    files_out["diag_train_oof.csv"] = df_diag.to_csv(index=False).encode("utf-8")
    files_out["diag_by_location.csv"] = df_loc_export.to_csv(index=False).encode("utf-8")

    # NPY: oof / y / test_pred
    # encode as npy bytes
    def npy_bytes(arr):
        b = io.BytesIO()
        np.save(b, np.asarray(arr))
        return b.getvalue()

    files_out["oof.npy"] = npy_bytes(oof.astype(np.float32))
    files_out["y.npy"] = npy_bytes(y.astype(np.float32))
    files_out["test_pred.npy"] = npy_bytes(test_pred.astype(np.float32))

    # keys
    files_out["train_keys.csv"] = train_keys.to_csv(index=False).encode("utf-8")
    files_out["test_keys.csv"] = test_keys.to_csv(index=False).encode("utf-8")

    # tab features + matrices if available
    if X_tab_train is not None:
        files_out["X_tab_train.npy"] = npy_bytes(nan_clean(X_tab_train).astype(np.float32))
    if X_tab_test is not None:
        files_out["X_tab_test.npy"] = npy_bytes(nan_clean(X_tab_test).astype(np.float32))

    if tab_feature_names is not None:
        files_out["tab_feature_names.csv"] = pd.Series(tab_feature_names).to_csv(index=False, header=False).encode("utf-8")

    # lgb outputs if computed
    res = st.session_state.get("lgb_results", {})
    if res:
        files_out["oof_lgb.npy"] = npy_bytes(res["oof_lgb"].astype(np.float32))
        files_out["lgb_importance_gain.csv"] = res["imp_df"].to_csv(index=False).encode("utf-8")
        files_out["lgb_importance_permutation.csv"] = res["perm_df"].to_csv(index=False).encode("utf-8")

    # Submission CSV (optional)
    sub = pd.DataFrame({ID_COL: test_keys[ID_COL].values, TARGET_COL: test_pred})
    files_out["submission.csv"] = sub.to_csv(index=False).encode("utf-8")

    zip_bytes = make_zip(files_out)

    st.download_button(
        label="Télécharger tous les artefacts (ZIP)",
        data=zip_bytes,
        file_name="airqo_streamlit_artifacts.zip",
        mime="application/zip"
    )

    st.write("Fichiers inclus dans le ZIP :", list(files_out.keys()))